### users CRUD operations (admin features)
GET http://localhost:3000/user/all
Authorization: Bearer token


###
GET http://localhost:3000/user/23
Authorization: Bearer token


### 
DELETE http://localhost:3000/user/24
Authorization: Bearer token


###
POST http://localhost:3000/user HTTP/1.1
Authorization: Bearer token
content-type: application/json

{
    "username": "newuser",
    "password": "password",
    "email": "email@mail.com",
    "roleId": 2
}

###
PATCH http://localhost:3000/user/23 HTTP/1.1
Authorization: Bearer token
content-type: application/json

{
    "username": "changeduser",
    "password": "chpass"
}



### Authentication
POST http://localhost:3000/auth/login HTTP/1.1
content-type: application/json

{
    "username": "admin",
    "password": "hardPassword"
}

###
POST http://localhost:3000/auth/registration HTTP/1.1
content-type: application/json

{
    "username": "superuser",
    "password": "hardPassword",
    "email": "email@mail.com",
    "roleId": 1
}


###
POST http://localhost:3000/auth/registration HTTP/1.1
content-type: application/json

{
    "username": "just_user",
    "password": "password",
    "email": "email@mail.com",
    "roleId": 2
}

### (user features)
GET http://localhost:3000/current/profile
Authorization: Bearer token

### 
DELETE http://localhost:3000/current/delete
Authorization: Bearer token


###
PATCH http://localhost:3000/current/update HTTP/1.1
Authorization: Bearer token
content-type: application/json

{
    "username": "changeduser",
    "password": "changedpassword"
}