###
GET http://localhost:3000/user/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNpbXBsZTEiLCJzdWIiOjIzLCJpYXQiOjE2NTUxODQ0NzksImV4cCI6MTY1NTE4NDUzOX0.Vj4dyVpLeKdVVCSNwYKUF8Ymk7winivVcqGlS3-dl3Q


###
GET http://localhost:3000/user/23
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwic3ViIjp7InVzZXJJZCI6MzgsInJvbGVOYW1lIjoiYWRtaW4ifSwiaWF0IjoxNjU1MjIzNTAxLCJleHAiOjE2NTUyMjM1NjF9.LtYzHLUkS_Tzgv6zfahIiFNdqju5x5ieXGwa6J13N6Y


### 
DELETE http://localhost:3000/user/24
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwic3ViIjp7InVzZXJJZCI6MzgsInJvbGVOYW1lIjoiYWRtaW4ifSwiaWF0IjoxNjU1MjIzNTAxLCJleHAiOjE2NTUyMjM1NjF9.LtYzHLUkS_Tzgv6zfahIiFNdqju5x5ieXGwa6J13N6Y


###
POST http://localhost:3000/user HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNpbXBsZTEiLCJzdWIiOjIzLCJpYXQiOjE2NTUxODQ0NzksImV4cCI6MTY1NTE4NDUzOX0.Vj4dyVpLeKdVVCSNwYKUF8Ymk7winivVcqGlS3-dl3Q
content-type: application/json

{
    "username": "user1",
    "password": "password",
    "email": "email@mail.com",
    "roleId": 1
}

###
PATCH http://localhost:3000/user/23 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwic3ViIjp7InVzZXJJZCI6MzgsInJvbGVOYW1lIjoiYWRtaW4ifSwiaWF0IjoxNjU1MjIzNTAxLCJleHAiOjE2NTUyMjM1NjF9.LtYzHLUkS_Tzgv6zfahIiFNdqju5x5ieXGwa6J13N6Y
content-type: application/json

{
    "username": "simple1",
    "password": "password3"
}



###
POST http://localhost:3000/auth/login HTTP/1.1
content-type: application/json

{
    "username": "admin",
    "password": "hardPassword"
}

###
POST http://localhost:3000/auth/registration HTTP/1.1
content-type: application/json

{
    "username": "admin",
    "password": "hardPassword",
    "email": "email@mail.com",
    "roleId": 1
}

###
GET http://localhost:3000/current/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwic3ViIjp7InVzZXJJZCI6MzksInJvbGVOYW1lIjoiYWRtaW4ifSwiaWF0IjoxNjU1MjI0NTUzLCJleHAiOjE2NTUyMjQ2MTN9.FhsZzYVvxA5vK-Vcy99t2ynGnLrl1QqxJSFHKC5VWzU

### 
DELETE http://localhost:3000/current/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwic3ViIjp7InVzZXJJZCI6MzksInJvbGVOYW1lIjoiYWRtaW4ifSwiaWF0IjoxNjU1MjI0NTUzLCJleHAiOjE2NTUyMjQ2MTN9.FhsZzYVvxA5vK-Vcy99t2ynGnLrl1QqxJSFHKC5VWzU


###
PATCH http://localhost:3000/current/update HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwic3ViIjp7InVzZXJJZCI6MzksInJvbGVOYW1lIjoiYWRtaW4ifSwiaWF0IjoxNjU1MjI0NTUzLCJleHAiOjE2NTUyMjQ2MTN9.FhsZzYVvxA5vK-Vcy99t2ynGnLrl1QqxJSFHKC5VWzU
content-type: application/json

{
    "username": "simple",
    "password": "password3"
}